#https://github.com/revolunet/create-react-app-circleci/blob/master/.circleci/config.yml
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - lib
            - package.json
            - LICENSE
            - README.md
      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - run: npm publish
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
