name: Publish

on:
  release:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  setup:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: wheckout
        uses: actions/checkout@master

      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install
        
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: restore cache from node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        
      - name: build
        run: yarn build
        
      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    needs: setup
